# Generated by Django 4.0.2 on 2023-05-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-last_name',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
