# Generated by Django 4.0.2 on 2023-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
