# Generated by Django 4.0.2 on 2023-05-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_alter_trade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('-trader__email',), 'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
    ]
