# Generated by Django 4.0.2 on 2023-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_alter_trade_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
