# Generated by Django 4.2.1 on 2023-06-01 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("traders", "0004_alter_trade_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
